/* eslint-disable no-param-reassign */
import { createSlice } from '@reduxjs/toolkit';
import type { PayloadAction } from '@reduxjs/toolkit';

import { LeagueTypes, User } from '@types';

const initialState: Array<User> = [
  {
    id: 0,
    userName: 'Yarikhot',
    name: 'Subhan Griffith',
    email: 'yarikhot@gmail.com',
    imageUrl: '/testImage.jpg',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 40,
    coinAmount: 300,
    league: LeagueTypes.Low,
  },
  {
    id: 1,
    userName: 'DonagQuipu',
    name: 'Mahdi Robinson',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test1.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 88,
    coinAmount: 300,
    league: LeagueTypes.Low,
  },
  {
    id: 2,
    userName: 'Mami04Bumf',
    name: 'Kaya Thatcher',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test2.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 100,
    coinAmount: 300,
    league: LeagueTypes.Medium,
  },
  {
    id: 3,
    userName: 'Piccadilly',
    name: 'Anabella Meyers',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test3.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 111,
    coinAmount: 300,
    league: LeagueTypes.Medium,
  },
  {
    id: 4,
    userName: 'Coemption',
    name: 'Anabella Meyers',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test3.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 222,
    coinAmount: 300,
    league: LeagueTypes.Medium,
  },
  {
    id: 5,
    userName: 'Skedaddle',
    name: 'Ricardo Poole',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test4.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 333,
    coinAmount: 300,
    league: LeagueTypes.Medium,
  },
  {
    id: 6,
    userName: 'Mondain',
    name: 'Shiv Mcfarlane',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test5.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 400,
    coinAmount: 300,
    league: LeagueTypes.Medium,
  },
  {
    id: 7,
    userName: 'Bywoner',
    name: 'Caoimhe Scott',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test6.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 800,
    coinAmount: 300,
    league: LeagueTypes.High,
  },
  {
    id: 8,
    userName: 'Monkey',
    name: 'Sumaya Gillespie',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test7.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 900,
    coinAmount: 300,
    league: LeagueTypes.High,
  },
  {
    id: 9,
    userName: 'Pseudodox',
    name: 'Penny Allison',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test8.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 1000,
    coinAmount: 300,
    league: LeagueTypes.High,
  },
  {
    id: 10,
    userName: 'Kahuna',
    name: 'Taio Lozano',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test9.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 1001,
    coinAmount: 300,
    league: LeagueTypes.High,
  },
  {
    id: 11,
    userName: 'Kahuna',
    name: 'Tnui Munuo',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test10.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 1020,
    coinAmount: 300,
    league: LeagueTypes.High,
  },
  {
    id: 12,
    userName: 'DonagQuipu',
    name: 'Tom Black',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test1.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 19,
    coinAmount: 300,
    league: LeagueTypes.Low,
  },
  {
    id: 13,
    userName: 'DonagQuipu',
    name: 'Leo Robion',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test1.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 18,
    coinAmount: 300,
    league: LeagueTypes.Low,
  },
  {
    id: 13,
    userName: 'DonagQuipu',
    name: 'Sam Smith',
    email: 'yarikhot@gmail.com',
    imageUrl: '/test7.png',
    password: 'Caramba2022.',
    isAuthorized: true,
    score: 2,
    coinAmount: 300,
    league: LeagueTypes.Low,
  },
];

export const usersSlice = createSlice({
  name: 'users',
  initialState,
  reducers: {
    addUser: (state, action: PayloadAction<User>) => {
      state.push(action.payload);
    },
  },
});

// Action creators are generated for each case reducer function
export const { addUser } = usersSlice.actions;

export const useresReducres = usersSlice.reducer;
